// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnbpfxhfnaayoxhtyfzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uYnBmeGhmbmFheW94aHR5Znp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMTc5NjcsImV4cCI6MjA1NTY5Mzk2N30.cC2OF5B13AECwgawBW8Dvr50yDOij8hPdvWlR-y2jMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);